name: Deploy to s3

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      # AWS認証（OIDCを利用）
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1 # 東京リージョン

      # S3へデプロイ（ファイルを同期）
      - name: Deploy to S3
        run: |
          aws s3 sync ./dist s3://ztoy-s3-docs-test-026777907138-ap-northeast-1-an --delete
